name = "mangaplus"
compatibility_date = "2024-09-23"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "CACHE"
id = "44c13b24ac0b4302b395985ca16e2aa1"

[[d1_databases]]
binding = "DB"
database_name = "mangaplus"
database_id = "0ea320b1-b22f-4ed3-9533-0d8431e53395"
